/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      hideInMenu: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'questions',
    path: '/questions',
    component: 'layout.base$view.questions',
    meta: {
      title: 'questions',
      i18nKey: 'route.questions',
      icon: 'mdi:question-box-multiple-outline'
    }
  },
  {
    name: 'user-manager',
    path: '/user-manager',
    component: 'layout.base',
    meta: {
      title: 'user-manager',
      i18nKey: 'route.user-manager',
      icon: 'majesticons:users-line'
    },
    children: [
      {
        name: 'user-manager_admin-user',
        path: '/user-manager/admin-user',
        component: 'view.user-manager_admin-user',
        meta: {
          title: 'user-manager_admin-user',
          i18nKey: 'route.user-manager_admin-user',
          icon: 'mingcute:user-star-line',
          roles: ['SUPER_ADMIN']
        }
      },
      {
        name: 'user-manager_common-user',
        path: '/user-manager/common-user',
        component: 'view.user-manager_common-user',
        meta: {
          title: 'user-manager_common-user',
          i18nKey: 'route.user-manager_common-user',
          icon: 'mdi:user-circle-outline'
        }
      }
    ]
  }
];
