/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/app/app-provider.vue')['default']
    ContextHolder: typeof import('./src/components/app/context-holder.vue')['default']
    Icon: typeof import('./src/components/common/Icon.vue')['default']
    ModuleTag: typeof import('./src/components/common/module-tag.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NPopover: typeof import('naive-ui')['NPopover']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    QuestionOrders: typeof import('./src/components/common/question-orders.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskButton: typeof import('./src/components/common/task-button.vue')['default']
    UserButton: typeof import('./src/components/common/user-button/user-button.vue')['default']
    UserOperationList: typeof import('./src/components/common/user-button/user-operation-list.vue')['default']
  }
}
